CREATE TABLE IF NOT EXISTS movement (
	mvmt_id TEXT NOT NULL, 
	node_id TEXT NOT NULL, 
	name TEXT, 
	ib_link_id TEXT NOT NULL, 
	start_ib_lane INTEGER, 
	end_ib_lane INTEGER, 
	ob_link_id TEXT NOT NULL, 
	start_ob_lane INTEGER, 
	end_ob_lane INTEGER, 
	type VARCHAR(7) NOT NULL, 
	penalty FLOAT, 
	capacity FLOAT, 
	ctrl_type VARCHAR(16), 
	mvmt_code TEXT, 
	allowed_uses TEXT, 
	geometry TEXT, 
	PRIMARY KEY (mvmt_id), 
	FOREIGN KEY(node_id) REFERENCES node (node_id), 
	FOREIGN KEY(ib_link_id) REFERENCES link (link_id), 
	FOREIGN KEY(ob_link_id) REFERENCES link (link_id)
)